### ISSUE TITLE
Cookie set without the 'SameSite' attriubute

### ISSUE THREAD

**Issue by jamesamuel** [elastic/app-search-javascript#26]
This issue is prompting multiple client warnings.

Using v7.8.0

`A cookie associated with a cross-site resource at http://swiftype.com/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.`

**Comment by JasonStoltz** [comment]
Hey @jamesamuel. It's likely that cookies are being sent on our API requests that were set elsewhere, like when visiting swiftype.com.

I don't believe there is any cause for concern here. I additionally don't believe it's related to this client. Your users won't see that, you're likely only seeing it because of you've visited one of the above previously.

I'm going to close this issue for now. Thank you for reporting it.
